INSERT INTO kategori_banmods(id,jenis,nama) VALUES
 (1,1,'BURUH PABRIK ROKOK')
,(2,1,'BURUH TANI TEMBAKAU')
,(3,1,'PEKERJA PABRIK ROKOK')
,(4,2,'INDUSTRI KECIL DAN MENENGAH')
,(5,1,'MASYARAKAT MISKIN')
,(6,1,'PEDAGANG KAKI LIMA')
