INSERT INTO ref_pendidikans(id,nama) VALUES
(1,'TIDAK/BELUM SEKOLAH'),
(2,'BELUM TAMAT SD/SEDERAJAT'),
(3,'TAMAT SD/SEDERAJAT'),
(4,'SMP/SEDERAJAT'),
(5,'SMA/SEDERAJAT'),
(6,'DIPLOMA I/II'),
(7,'AKADEMI/DIPLOMA III/S. MUDA'),
(8,'DIPLOMA IV/STRATA I'),
(9,'STRATA II'),
(10,'STRATA III');
