INSERT INTO skor_pelatihan_petanis(id,jenis,nama,skor) VALUES
(1,1,'DENGAN MENGIKUTI PELATIHAN INI BISA MENINGKATKAN PRODUKTIVITAS PERTANIAN/PETERNAKAN/PERIKANAN, SERTA PENINGKATAN PEREKONOMIAN KELUARGA',3),
(2,1,'DENGAN MENGIKUTI PELATIHAN INI SAYA MENDAPATKAN KETERAMPILAN PRAKTIS YANG DAPAT LANGSUNG DITERAPKAN ',2),
(3,1,' DAPAT MENDAPATAN WAWASAN BARU ',1)